//
// Created by Diego on 04/01/2023.
//

#ifndef EJERCICIOSEEDD_INTERNATIONALCONGRESS_H
#define EJERCICIOSEEDD_INTERNATIONALCONGRESS_H


class InternationalCongress {

};


#endif //EJERCICIOSEEDD_INTERNATIONALCONGRESS_H
